color_theme = "dracula"
theme_background = True
truecolor = True
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_per_core = True
proc_mem_bytes = True
proc_cpu_graphs = True
show_uptime = True
check_temp = True
cpu_sensor = "Auto"
show_coretemp = True
temp_scale = "celsius"
show_cpu_freq = True
clock_format = "%H:%M"
custom_cpu_name = "Intel i5-5250U (Broadwell)"
net_auto = True
show_battery = True
selected_battery = "Auto"
mem_graphs = True
